apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-web-app
  labels:
    app: basic-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-web-app
  template:
    metadata:
      name: basic-web-app
      labels:
        app: basic-web-app
    spec:
      containers:
      - name: basic-web-app
        image: msassigment.azurecr.io/basic-web-app:v0.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: basic-web-app

---
apiVersion: v1
kind: Service
metadata:
  name: basic-web-app
spec:
  selector:
    app: basic-web-app
  ports:
    - port: 80
      name: http
      targetPort: basic-web-app

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-web-app
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /webapp
        pathType: Prefix
        backend:
          service:
            name: basic-web-app
            port:
              number: 80

---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: basic-web-app-allow-nginx-only
spec:
  podSelector:
    matchLabels:
      app: basic-web-app
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx



